baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'dirman hana'
theme = 'etch'

[[menu.main]]
  name ="Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2
